/**
 * Static catalog: game copy, controls, categories and badge definitions.
 * Rich presentation data lives in code; the authoritative rows the server
 * enforces against live in Supabase (`games`, `achievements`). Keep slugs
 * and ids in sync with supabase/migrations.
 */
import type { BadgeDef, Game, GameCategory, PlayerSummary } from "./types";

export const CATEGORIES: { id: GameCategory; label: string }[] = [
  { id: "shooter", label: "Shooter" },
  { id: "sim", label: "Sim" },
  { id: "strategy", label: "Strategy" },
  { id: "sports", label: "Sports+" },
];

export const GAMES: Game[] = [
  {
    slug: "neon-siege",
    title: "Neon Siege",
    tagline: "Drop in. Loot up. Be the last one standing.",
    description:
      "A battle royale shooter in a fully 3D town. Drop in with 15 AI fighters, loot weapons from common to legendary, crack open chests, outrun the closing storm and fight for the win. Season 1: Ground Zero brings a free 30-tier battle pass with outfits, weapon wraps and banners, plus online deathmatch rooms with friends.",
    category: "shooter",
    tags: ["battle royale", "fps", "3d", "multiplayer", "bots"],
    status: "live",
    palette: ["#ffb321", "#4d6334"],
    rating: 0,
    ratingCount: 0,
    plays: 0,
    releasedAt: "2026-09-29",
    controls: [
      { keys: ["W", "A", "S", "D"], action: "Move / strafe" },
      { keys: ["Mouse"], action: "Look (click the game to lock the pointer)" },
      { keys: ["Click", "Space"], action: "Fire / use item" },
      { keys: ["Right-click", "Z"], action: "Aim down sights" },
      { keys: ["E"], action: "Pick up loot / open chest" },
      { keys: ["1–5", "Wheel"], action: "Switch hotbar slot" },
      { keys: ["R"], action: "Reload" },
      { keys: ["←", "→"], action: "Turn (keyboard only)" },
      { keys: ["Tab"], action: "Scoreboard (online)" },
      { keys: ["Esc", "P"], action: "Pause" },
    ],
    orientation: "landscape",
    touchControls:
      "Left thumb drags a virtual stick to move, right thumb drags to look. Hold FIRE to shoot, R to reload.",
  },
  {
    slug: "trenches",
    title: "Trenches",
    tagline: "Hold the line. Take the flags. Bleed their tickets dry.",
    description:
      "A realistic 3D Great War shooter. Fight at Gallipoli, the Somme, Verdun, Passchendaele, Vimy Ridge and the Argonne Forest, or storm Cape Helles. Three modes: Classic (hold the flags, bleed their tickets), Breakthrough (attack sector by sector) and Frontline (beach, two villages, no-man's-land, then the HQ, with only 3 redeploys). Build your loadout, dig in, throw Mills bombs and call in artillery, supply drops and recon flares. Play in multiplayer lobbies or vs bots. New in the Over the Top update: poison gas and gas masks, bayonet charges, emplaced Vickers guns and medics who revive the fallen.",
    category: "shooter",
    tags: ["war", "fps", "3d", "multiplayer", "lobbies", "conquest", "bots"],
    status: "live",
    palette: ["#c9a24a", "#6b6a45"],
    rating: 0,
    ratingCount: 0,
    plays: 0,
    releasedAt: "2026-09-30",
    controls: [
      { keys: ["W", "A", "S", "D"], action: "Move / strafe" },
      { keys: ["Mouse"], action: "Look (click the game to lock the pointer)" },
      { keys: ["Click", "Space"], action: "Fire / use item" },
      { keys: ["Right-click", "Z"], action: "Aim down sights" },
      { keys: ["1–5", "Wheel"], action: "Switch weapon / item" },
      { keys: ["R"], action: "Reload" },
      { keys: ["V"], action: "Bayonet (charge while sprinting)" },
      { keys: ["M"], action: "Gas mask on / off" },
      { keys: ["E"], action: "Man a Vickers gun · revive a fallen teammate (medics)" },
      { keys: ["B", "N", "T", "H"], action: "Call artillery, supplies, a recon flare, gas shells" },
      { keys: ["Tab"], action: "Scoreboard" },
      { keys: ["Esc", "P"], action: "Pause" },
    ],
    orientation: "landscape",
    touchControls:
      "Left thumb drags a virtual stick to move, right thumb drags to look. Hold FIRE to shoot, R to reload.",
  },
  {
    slug: "code-3",
    title: "Code 3",
    tagline: "Lights. Sirens. Justice. Work the beat in Bayview.",
    description:
      "A police patrol sim in a full 3D city. Suit up, take your cruiser out of the station and work a night or day shift in Bayview: answer dispatch callouts (armed robberies, shots fired, stolen cars, drunk drivers, collisions, domestics, street races and bank jobs), run traffic stops by the book (licence, MDT plate and warrant checks, questions, breathalyzer, consent and probable-cause searches, citations), chase fleeing suspects with PIT manoeuvres and backup, tackle and tase runners, cuff them, and book them at the station. Traffic obeys the lights and pulls over for your siren. Every call is scored: good police work ranks you up from Cadet to Chief and unlocks faster units.",
    category: "sim",
    tags: ["police", "driving", "open world", "3d", "pursuits"],
    status: "live",
    palette: ["#3b82f6", "#ef4444"],
    rating: 0,
    ratingCount: 0,
    plays: 0,
    releasedAt: "2026-10-02",
    controls: [
      { keys: ["W", "S"], action: "Throttle / brake & reverse (walk on foot)" },
      { keys: ["A", "D"], action: "Steer (strafe on foot)" },
      { keys: ["Space"], action: "Handbrake" },
      { keys: ["Q"], action: "Lights → lights + siren → off" },
      { keys: ["H"], action: "Siren yelp" },
      { keys: ["E"], action: "Exit / enter your unit" },
      { keys: ["Mouse"], action: "Look / aim (click the game to lock the pointer)" },
      { keys: ["Click", "F"], action: "Fire taser / sidearm" },
      { keys: ["Right-click"], action: "Aim" },
      { keys: ["X"], action: "Switch taser / sidearm" },
      { keys: ["G"], action: "Shout \"Police! Stop!\"" },
      { keys: ["1–9"], action: "Actions: talk, ID, MDT, search, cite, arrest…" },
      { keys: ["Y", "N"], action: "Respond to / decline a dispatch call" },
      { keys: ["B"], action: "Call for backup" },
      { keys: ["Tab"], action: "Mobile data terminal (MDT)" },
      { keys: ["C"], action: "Camera distance" },
      { keys: ["Esc", "P"], action: "Pause" },
    ],
    orientation: "landscape",
    touchControls:
      "Left thumb drives or walks, right thumb looks around. Buttons for enter/exit, lights, handbrake, fire, aim and backup; tap the action list to talk, search, cite and arrest.",
  },
  {
    slug: "aussie-rules",
    title: "Screamer: Aussie Rules",
    tagline: "Take a screamer. Slot it from 50. Win the flag.",
    description:
      "Full 18-a-side Australian rules football on a floodlit 3D oval. Four quarters, centre bounces, kicks, handballs, bounces, marks and set shots, tackles and holding-the-ball, kick-ins, throw-ins and behinds. The mega update: a Premiership season with eight clubs, a ladder, finals and a Grand Final (lift the cup), drop punts, torpedoes and curling snaps, rain that greases the ball, goal replays, live commentary, and 3-2-1 best-on-ground votes. Now with a women's competition, the League Medal count and leading goalkicker across a season, score reviews on close calls, and a goalkicking challenge. Coach mode puts you in the box: pick the eighteen from a list of thirty, set the game plan and training, give the speech at every break, survive the board, then trade and draft each off-season. Premierships roll on year after year with an honour board, form guides, round-by-round results and awards night read out live, and Grand Final day gets the parade, fireworks, the banners, the cup and the Grand Final Medal. Lead into space, take a screamer on someone's shoulders and kick the winner after the siren. Needs the Sports+ pass (50 coins, once).",
    category: "sports",
    tags: ["football", "aussie rules", "3d", "sports+"],
    status: "live",
    palette: ["#e11d48", "#1d4ed8"],
    rating: 0,
    ratingCount: 0,
    plays: 0,
    releasedAt: "2026-10-03",
    pass: "sports-plus",
    controls: [
      { keys: ["W", "A", "S", "D"], action: "Run (camera-relative)" },
      { keys: ["Shift"], action: "Sprint" },
      { keys: ["Space", "Click"], action: "Hold to charge a kick, release to kick (aim with the mouse / at the goals)" },
      { keys: ["F", "Right-click"], action: "Handball to the nearest teammate" },
      { keys: ["E"], action: "Jump for a mark / spoil (without the ball); tackle when close" },
      { keys: ["Q"], action: "Switch to the player nearest the ball" },
      { keys: ["B"], action: "Bounce (every 15 m while running)" },
      { keys: ["R"], action: "Kick style: drop punt, torpedo, snap" },
      { keys: ["C"], action: "Camera: broadcast / behind the player" },
      { keys: ["Esc", "P"], action: "Pause" },
    ],
    orientation: "landscape",
    touchControls:
      "Left thumb runs. Hold KICK and release to kick (longer hold = longer kick), STYLE switches punt / torpedo / snap, tap HANDBALL to dish off, MARK to leap, TACKLE when close, SWITCH to take the player nearest the ball.",
  },
  {
    slug: "diamond-derby",
    title: "Diamond Derby",
    tagline: "Ten outs. One swing at a time. Clear the wall.",
    description:
      "A Sports+ home run derby in a full 3D ballpark. Aim the plate coverage circle, read the pitch (riding fastballs, fading changeups, 12-to-6 curves, sweeping sliders) and time your swing. Every ball you don't hit out is an out: beat the AI slugger's mark in the quarterfinal, semifinal and final to take the title. Real batted-ball flight with drag and backspin, Statcast readouts for every swing, fireworks for every homer, day, twilight or night. Needs the Sports+ pass (50 coins, once).",
    category: "sports",
    tags: ["baseball", "home run derby", "3d", "sports+"],
    status: "live",
    palette: ["#d61f3a", "#13284d"],
    rating: 0,
    ratingCount: 0,
    plays: 0,
    releasedAt: "2026-10-05",
    pass: "sports-plus",
    controls: [
      { keys: ["Mouse"], action: "Aim the plate coverage circle" },
      { keys: ["W", "A", "S", "D"], action: "Nudge the aim" },
      { keys: ["Click", "Space"], action: "Swing" },
      { keys: ["C"], action: "Camera: batter / centre field" },
      { keys: ["Esc", "P"], action: "Pause" },
    ],
    orientation: "landscape",
    touchControls: "Drag anywhere to move the aim circle, tap SWING as the ball arrives. CAM switches between the batter's view and the centre-field camera.",
  },
  {
    slug: "ace-rally",
    title: "Ace Rally",
    tagline: "Toss. Serve. Rally. Break. Hold. Win it on Centre Court.",
    description:
      "Sports+ singles tennis at the Zero X Open, in a full 3D stadium. Time your toss for a 200 km/h first serve, then slug it out with topspin, slice, lobs and drop shots against touring pros with their own styles. Real ball flight with spin and drag, hard, clay or grass (each bounces its own way), full scoring with deuce, advantage and tiebreaks, Hawk-Eye on close calls, an umpire who calls the score, and men's and women's draws. Needs the Sports+ pass (50 coins, once).",
    category: "sports",
    tags: ["tennis", "3d", "sports+"],
    status: "live",
    palette: ["#15803d", "#d9f99d"],
    rating: 0,
    ratingCount: 0,
    plays: 0,
    releasedAt: "2026-10-06",
    pass: "sports-plus",
    controls: [
      { keys: ["W", "A", "S", "D"], action: "Move (and aim as you hit)" },
      { keys: ["Space", "Click", "J"], action: "Serve (toss, then hit) / topspin" },
      { keys: ["K", "Right-click"], action: "Slice" },
      { keys: ["L"], action: "Lob" },
      { keys: ["I"], action: "Drop shot" },
      { keys: ["C"], action: "Camera: broadcast / player" },
      { keys: ["Esc", "P"], action: "Pause" },
    ],
    orientation: "landscape",
    touchControls: "Left thumb moves you and aims your shot as you hit. SERVE (tap to toss, tap at the top to hit) turns into TOPSPIN in the rally; SLICE, LOB and DROP sit beside it.",
  },
  {
    slug: "hometown",
    title: "Hometown",
    tagline: "One town, everyone in it. Work, build, trade, run for mayor.",
    description:
      "A persistent online town shared by every signed-in player. Work shifts at the farm, the timber yard and the mine for raw goods and pay, or do public works for the wage the mayor sets. Buy a lot and build your house wall by wall (each wall takes a plank, each piece of furniture comes from a workshop) for everyone who walks past to see. Found a business on your land: mills, bakeries, sawmills, workshops, foundries and smithies turn one player's goods into another's. Trade on the Town Exchange, a real order book where bids and asks match at the best price, or open a shop and stock its shelves at your own prices. Every sale pays sales tax into the treasury, and every six hours the town elects a mayor who sets the tax and the public wage. See your neighbours walking the streets and chat as you go. The server keeps every coin and crate, so the economy is real: prices are whatever players make them.",
    category: "sim",
    tags: ["online", "economy", "building", "3d", "elections"],
    status: "live",
    palette: ["#b45309", "#facc15"],
    rating: 0,
    ratingCount: 0,
    plays: 0,
    releasedAt: "2026-10-11",
    controls: [
      { keys: ["W", "A", "S", "D"], action: "Walk (Shift to run)" },
      { keys: ["Mouse drag"], action: "Look around" },
      { keys: ["E"], action: "Enter a building · visit a lot" },
      { keys: ["M"], action: "Phone: bag, market, Gazette" },
      { keys: ["B"], action: "Build on your lot" },
      { keys: ["R"], action: "Rotate furniture (build)" },
      { keys: ["Enter", "T"], action: "Chat" },
      { keys: ["Esc", "P"], action: "Pause" },
    ],
    orientation: "landscape",
    touchControls: "The left thumb walks and dragging on the right looks around. Tap the prompt to go in, PHONE for your bag and the market, BUILD on your own lot, and 💬 to chat.",
  },
  {
    slug: "ubusiness",
    title: "UBusiness",
    tagline: "Open the doors. Stock the shelves. Build a retail empire.",
    description:
      "Run your own store, from a corner shop to a megastore, in a photoreal 3D building with daylight pouring through the front windows. Order stock from the wholesaler and watch the boxes arrive in your stockroom, fill the shelves, fridges and produce stands, and set every price yourself: shoppers judge each one against what it usually costs, and a store they like will pay a little more. Work the till yourself (scan each item, take the card or count out the change) or hire cashiers and stockers. Buy licences for new departments, grow into bigger premises, keep the place busy at lunch and after work, and close the books every evening: rent, wages and power come out, XP and your level go up. The big expansion adds frozen food and a bakery (fresh food goes off overnight, so order what you'll sell), specials that pull shoppers in, eight store upgrades from tap-to-pay to a loyalty app, bank loans, sixteen trophies, shopper reviews, shoplifters to catch (or a guard to catch them), Halloween, match-day and school-holiday rushes, and a discount rival that opens across the street on day 6. Lite (5 ZX Cash) runs grocery, snacks, household, fresh and frozen up to a Mini Market with one member of staff. Ultimate (30 ZX Cash, free with the battle pass, and free for everyone to claim until 31 October) adds the bakery, health and beauty, toys, fashion and electronics, six store sizes, a team of six, self-checkouts, marketing campaigns, express delivery, 3× speed and photo mode.",
    category: "sim",
    tags: ["management", "retail", "economy", "3d", "photoreal"],
    status: "live",
    palette: ["#0f766e", "#f59e0b"],
    rating: 0,
    ratingCount: 0,
    plays: 0,
    releasedAt: "2026-10-16",
    pass: "ubusiness",
    controls: [
      { keys: ["Mouse drag"], action: "Look around the store" },
      { keys: ["Wheel"], action: "Zoom" },
      { keys: ["W", "A", "S", "D"], action: "Move the camera" },
      { keys: ["Click"], action: "Use a shelf, the till or the computer" },
      { keys: ["Space"], action: "Scan the next item at the till" },
      { keys: ["B"], action: "Build mode" },
      { keys: ["R"], action: "Rotate (build)" },
      { keys: ["Esc", "P"], action: "Pause" },
    ],
    orientation: "landscape",
    touchControls: "Drag to look around, pinch to zoom, tap a shelf, the till or the office computer. The buttons along the bottom open stock, prices, staff and build.",
  },
  {
    slug: "linkwave",
    title: "Linkwave",
    tagline: "Link the nodes. Close the loop. Beat the clock.",
    description:
      "A ZLink+ exclusive. A board of glowing nodes and seventy-five seconds on the clock: drag through neighbours of one colour to link them, and let go to clear them. Close a loop and every node of that colour goes, with three more seconds on the clock. Link six and you leave a Pulse behind that clears everything around it; a loop leaves a Prism that clears its whole row and column, and power nodes set each other off. Quick links build a combo up to ×5. Members only: the leaderboard is ZLink+ players against each other.",
    category: "puzzle",
    tags: ["zlink+ exclusive", "puzzle", "arcade", "neon"],
    status: "live",
    palette: ["#8b5cff", "#22e5ff"],
    rating: 0,
    ratingCount: 0,
    plays: 0,
    releasedAt: "2026-10-19",
    pass: "zlink",
    controls: [
      { keys: ["Mouse drag"], action: "Link matching nodes; let go to clear" },
      { keys: ["Arrows", "WASD"], action: "Move the cursor" },
      { keys: ["Space", "Enter"], action: "Start a link / clear it" },
      { keys: ["Backspace"], action: "Drop the link" },
      { keys: ["Esc", "P"], action: "Pause" },
    ],
    orientation: "any",
    touchControls: "Drag your finger through matching nodes and lift to clear them. Come back to where you started to close a loop.",
  },
  {
    slug: "lifeline",
    title: "Lifeline",
    tagline: "Build a hospital. Save lives.",
    description:
      "A 3D hospital management sim. Start with an empty plot and two workmen: lay foundations, walls and doors, and watch your workmen carry in the materials the truck drops off and build it brick by brick. Paint rooms and fill them with reception desks, waiting seats, consulting couches, ward beds, X-ray machines, trauma bays and operating tables, then hire doctors, nurses, surgeons, receptionists and janitors. Patients walk in (or arrive by ambulance) with flu, broken arms, appendicitis or heart attacks, check in, wait, get diagnosed and go through every step of their treatment, while you keep staff rested, floors clean before infections spread, the generator big enough for your machines and the books balanced. Unlock surgery and loans through bureaucracy, earn grants, ride out bus crashes, heatwaves and inspections, and climb to a five-star reputation. The mega update adds research, intensive care, maternity, psychiatry, an MRI suite and a helipad for air ambulances, staff who level up, machines that break down, and a five-scenario campaign with medals. Lives saved is your score.",
    category: "sim",
    tags: ["hospital", "management", "3d", "builder"],
    status: "live",
    palette: ["#2dd4bf", "#fb7185"],
    rating: 0,
    ratingCount: 0,
    plays: 0,
    releasedAt: "2026-10-25",
    controls: [
      { keys: ["Click", "Drag"], action: "Use the build tool; drag with no tool to pan" },
      { keys: ["Right drag", "Q", "E"], action: "Turn the camera" },
      { keys: ["Wheel"], action: "Zoom" },
      { keys: ["WASD", "Arrows"], action: "Pan" },
      { keys: ["R"], action: "Rotate the object you're placing" },
      { keys: ["C"], action: "Full-height or cut-away walls" },
      { keys: ["Space", "1", "2", "3"], action: "Pause and game speed" },
      { keys: ["Esc"], action: "Put the tool down" },
    ],
    orientation: "landscape",
    touchControls: "Pick a tool from the bar and drag on the plot to build. With no tool, drag to pan; pinch to zoom and twist to turn. Tap a person or a room to see how they're doing.",
  },
  {
    slug: "zero-city",
    title: "Zero City",
    tagline: "Draw roads. Paint zones. Watch a city come alive.",
    description:
      "The ZLink+ exclusive city builder. Pick one of ten maps, from flat farmland to river crossings, island chains and mountain ridges, and lay roads off the highway in eight ways: straight, curves, S-curves, freehand, roundabouts, lane layouts, one-ways and upgrades, with bridges and cuttings built for you. Paint homes, shops, industry and mixed-use beside your streets and watch red-brick walk-ups, cream mid-rises and glass towers rise on their own, while cars, vans, buses and people fill the streets, queue at junctions and cross at zebras. Tilt down to street level, click any car to see where it's going, and grow from a hamlet to a city of thousands through day and night. Play Sandbox with unlimited money, or Mayor mode: set taxes, balance the budget, win over five groups of voters, get policies through a seven-seat council, answer dilemmas and keep your promises before every election. Liquid-glass interface, eight languages. Members only.",
    category: "sim",
    tags: ["zlink+ exclusive", "city builder", "3d", "sandbox", "politics"],
    status: "live",
    palette: ["#22e5ff", "#f5a25a"],
    rating: 0,
    ratingCount: 0,
    plays: 0,
    releasedAt: "2026-10-24",
    pass: "zlink",
    controls: [
      { keys: ["1", "–", "8"], action: "Roads, Zoning, Transit, Terrain, Build, Move, Land, Bulldoze" },
      { keys: ["Click", "Drag"], action: "Use the tool" },
      { keys: ["Right drag", "Middle drag"], action: "Orbit and tilt" },
      { keys: ["WASD", "Arrows"], action: "Pan" },
      { keys: ["Q", "E"], action: "Rotate" },
      { keys: ["Wheel"], action: "Zoom" },
      { keys: ["Shift"], action: "Freeform road" },
      { keys: ["Ctrl", "Z"], action: "Undo" },
      { keys: ["Esc"], action: "Cancel" },
    ],
    orientation: "landscape",
    touchControls: "Pick a tool and drag with one finger to build; with no tool, one finger pans. Two fingers pinch to zoom, twist to rotate and slide up or down together to tilt. Tap a car to see its route.",
  },
  {
    slug: "yourgov",
    title: "YourGov",
    tagline: "Lead a party. Write the laws. Win the country, county by county.",
    description:
      "The ZLink+ exclusive politics sim. Play the made-up Federation of Avalon or one of twelve real countries (the United States, the United Kingdom, Canada, Australia, Germany, France, Spain, Italy, Japan, India, Brazil and Mexico), each a photoreal 3D map of its real regions, cities and mountains, with its real parties and starting seats, and its own political system: first past the post, two rounds, preferential voting, mixed-member and parallel systems and party lists; Presidents with vetoes and an electoral college, Prime Ministers who need the confidence of parliament, coalition talks, snap elections, Senates elected in thirds, appointed Lords and a Bundesrat. Or build your own country in the scenario studio: generate a continent, an island or an archipelago, found the parties, write the constitution and share it as a code. Every turn is a week: hold rallies, interviews and fundraisers, write bills on thirty laws or draft your own, steer them through committee and both houses, vote, pass the budget, keep your promises, and watch the elections come in county by county. A twenty-year career: your score is every law passed, seat won and promise kept. Members only.",
    category: "strategy",
    tags: ["zlink+ exclusive", "politics", "turn-based", "elections", "strategy", "real countries"],
    status: "live",
    palette: ["#8d8d8d", "#3d6fd8"],
    rating: 0,
    ratingCount: 0,
    plays: 0,
    releasedAt: "2026-10-30",
    pass: "zlink",
    controls: [
      { keys: ["Click"], action: "Open panels, pick a state on the map, vote" },
      { keys: ["Drag", "Wheel"], action: "Pan and zoom the map" },
      { keys: ["Enter", "Space"], action: "End the week" },
    ],
    orientation: "landscape",
    touchControls: "Tap the icons down the left to open panels, tap a state to choose where to campaign, drag and pinch the map, and tap the hourglass to end the week.",
  },
  {
    slug: "zenith",
    title: "Zenith",
    tagline: "Build a city. Watch it come alive.",
    description:
      "The ZLink+ flagship: a photoreal city builder. Start with a river valley, a strip of woods and a highway in, then lay roads, paint homes, shops and industry, and keep the power on and the water running. Buildings move in on their own, light their windows at night and climb from cottages to towers as land value rises; traffic fills the streets and chimneys smoke. Balance taxes against upkeep, cover the city with police, fire, clinics, hospitals and schools, check land value and pollution on the data views, and grow from Hamlet to Metropolis. Your population is your score. Members only.",
    category: "sim",
    tags: ["zlink+ exclusive", "city builder", "3d", "strategy"],
    status: "live",
    palette: ["#38bdf8", "#34d399"],
    rating: 0,
    ratingCount: 0,
    plays: 0,
    releasedAt: "2026-10-21",
    pass: "zlink",
    retiring: {
      on: "2026-11-30",
      successor: "zero-city",
      note: "Zenith is retiring. It stays playable for ZLink+ members until 30 November 2026, then closes for good. Its city builder lives on in Zero City, with Mayor mode, politics, roadworks and a far bigger toolset, and ZLink+ members now also get YourGov.",
    },
    controls: [
      { keys: ["Mouse drag"], action: "Lay roads, zone and bulldoze with a tool; pan without one" },
      { keys: ["Right drag"], action: "Rotate the camera" },
      { keys: ["Wheel", "R", "F"], action: "Zoom" },
      { keys: ["WASD", "Arrows"], action: "Pan" },
      { keys: ["Q", "E"], action: "Rotate" },
      { keys: ["Space"], action: "Pause or run the city" },
      { keys: ["1", "2", "B"], action: "Roads, zones, bulldoze" },
      { keys: ["Esc"], action: "Put the tool down" },
    ],
    orientation: "landscape",
    touchControls:
      "Pick a tool from the bar and drag on the map to build. With no tool, drag to pan; use two fingers to zoom and rotate. Tap a building to see how it's doing.",
  },
  {
    slug: "life",
    title: "Life",
    tagline: "Be born. Grow up. Build your house. Leave a legacy.",
    description:
      "The Zero X flagship: a whole life in Harbour City. Year by year on your phone, you grow up, go to school and university, get jobs and promotions, fall in love, marry, have kids, buy cars and houses, take risks, deal with whatever life throws at you and choose what happens next, until you die and carry on as one of your children. Day by day, you live it in a photoreal 3D town: walk Main Street, keep your hunger, energy, hygiene and fun up with what's in your house, work real shifts at the register, the café and on pizza runs, drive your own car, and buy a plot to build your dream house wall by wall, room by room, and furnish it. Every day you play feeds back into your year.",
    category: "sim",
    tags: ["life sim", "building", "3d", "open world", "flagship"],
    status: "live",
    palette: ["#10b981", "#f59e0b"],
    rating: 0,
    ratingCount: 0,
    plays: 0,
    releasedAt: "2026-10-09",
    controls: [
      { keys: ["Age up"], action: "Live the next year (phone)" },
      { keys: ["W", "A", "S", "D"], action: "Walk (Shift to run) / drive" },
      { keys: ["Mouse drag"], action: "Look around" },
      { keys: ["E"], action: "Use furniture · enter shops · deliver" },
      { keys: ["F"], action: "Get in / out of your car" },
      { keys: ["B"], action: "Build mode (your own home)" },
      { keys: ["R"], action: "Rotate furniture (build)" },
      { keys: ["M"], action: "End the day (back to your phone)" },
      { keys: ["Esc", "P"], action: "Pause" },
    ],
    orientation: "landscape",
    touchControls: "Your life plays on the phone screen: tap Age up, tabs and choices. In 3D, the left thumb walks or drives and dragging on the right looks around; USE, CAR, BUILD and PHONE buttons do the rest.",
  },
  {
    slug: "fairway",
    title: "Fairway",
    tagline: "Links or parkland. Read the wind, flush the iron, hole the putt.",
    description:
      "Sports+ golf on two original nine-hole courses: Saltgrass Links, out on the dunes with pot bunkers, fescue and the sea down the side, and Ironbark Hills, gum-lined parkland with lakes and big greens. Every shot is a real ball flight (launch, spin, drag and lift, wind that pushes harder the higher it goes), then it bounces and runs by the lie and the slope: fairways run, rough grabs, sand kills it, high wedges check on the greens. Swing on the classic three-press meter, where early fades and late draws, pick from 13 clubs with your caddie's suggestion, read the break from the arrows on the green and hole out. Stroke play against 11 touring pros with Stableford points, or closest to the pin with five balls at a par 3. Needs the Sports+ pass (50 coins, once).",
    category: "sports",
    tags: ["golf", "3d", "sports+"],
    status: "live",
    palette: ["#15803d", "#facc15"],
    rating: 0,
    ratingCount: 0,
    plays: 0,
    releasedAt: "2026-10-10",
    pass: "sports-plus",
    controls: [
      { keys: ["A", "D", "←", "→"], action: "Aim (hold Shift for fine)" },
      { keys: ["W", "S", "↑", "↓"], action: "Change club (putting: stroke length)" },
      { keys: ["Space", "Click"], action: "Swing: start, set power, stop on the line" },
      { keys: ["Esc", "P"], action: "Pause" },
    ],
    orientation: "landscape",
    touchControls: "◀ ▶ aim and − + change club. Tap SWING to start the meter, again to set the power and again on the white line.",
  },
  {
    slug: "boundary-blitz",
    title: "Boundary Blitz",
    tagline: "T20 cricket under lights. Time it. Loft it. Clear the rope.",
    description:
      "Sports+ T20 cricket in a full 3D stadium. Bat with an aim arrow, shot choice (along the ground, over the top or a solid block) and timing against real deliveries: swing and seam from the quicks, turn from the spinners, bouncers, yorkers and slower balls. Edges carry to the slips, fielders read the ball and take catches on the rope, and you push for the extra run at the risk of a run-out. Then bowl: pick the delivery, aim it on the pitch, set your field and hit the release meter. Full T20s (2, 5 or 20 overs) against the AI or a friend online, a super-over chase or the nets, the Blitz League (a season, semi-finals and a final, Orange and Purple Caps), DRS with ball-tracking, powerplays, full scorecards with a wagon wheel, eight franchises, LBWs, free hits and a crowd that goes up for every six. Needs the Sports+ pass (50 coins, once).",
    category: "sports",
    tags: ["cricket", "t20", "3d", "sports+"],
    status: "live",
    palette: ["#0e7490", "#f97316"],
    rating: 0,
    ratingCount: 0,
    plays: 0,
    releasedAt: "2026-10-08",
    pass: "sports-plus",
    controls: [
      { keys: ["Mouse"], action: "Aim your shot (the arrow on the ground)" },
      { keys: ["Click", "Space"], action: "Shot along the ground" },
      { keys: ["Right-click", "Shift", "F"], action: "Lofted shot" },
      { keys: ["S"], action: "Block" },
      { keys: ["R"], action: "Push for another run" },
      { keys: ["A", "D"], action: "Turn the aim" },
      { keys: ["Click pitch", "1–6", "F"], action: "Bowling: target, delivery, field" },
      { keys: ["Space ×2"], action: "Bowling: run in, release in the green" },
      { keys: ["C"], action: "Camera: broadcast / batter" },
      { keys: ["Esc", "P"], action: "Pause" },
    ],
    orientation: "landscape",
    touchControls: "Drag to swing the aim arrow, then SHOT, LOFT or BLOCK as the ball arrives; RUN pushes for another. Bowling: tap the pitch to aim, pick a delivery, BOWL to run in and BOWL again in the green.",
  },
  {
    slug: "clanforge",
    title: "Clanforge",
    tagline: "Build your village. Train your army. Raid for glory.",
    description:
      "A base-building strategy game in a sunlit 3D valley. Found a village around your Keep, put your builders to work on mines, wells, vaults and vats, and wall it in with cannons, archer towers, mortars, storm spires and air lances. Train brawlers, rangers, raiders, brutes, sappers and drakes, ask your clan for reinforcements, then raid AI villages for gold, mana and trophies: drop troops from the edge, knock out half the village for a star, the Keep for another and everything for three. Raiders hit back while you're away, so lay out your defenses well. Climb from Unranked to Legend league.",
    category: "strategy",
    tags: ["base building", "3d", "raids", "army"],
    status: "live",
    palette: ["#d97706", "#7c3aed"],
    rating: 0,
    ratingCount: 0,
    plays: 0,
    releasedAt: "2026-10-07",
    controls: [
      { keys: ["Drag"], action: "Pan the map" },
      { keys: ["Wheel", "+", "−"], action: "Zoom" },
      { keys: ["W", "A", "S", "D"], action: "Pan" },
      { keys: ["Click"], action: "Select a building / collect / deploy a troop" },
      { keys: ["Hold", "drag"], action: "Deploy a stream of troops" },
      { keys: ["1–7"], action: "Pick a troop in a raid" },
      { keys: ["Enter"], action: "Place the building" },
      { keys: ["Esc", "P"], action: "Pause" },
    ],
    orientation: "landscape",
    touchControls: "Drag to pan, pinch to zoom. Tap a building to select or collect it, drag the ghost to place one. In a raid, pick a troop at the bottom and tap or drag along the green edge to deploy.",
  },
];

export const FEATURED_SLUG = "life";

export function getGame(slug: string): Game | undefined {
  return GAMES.find((g) => g.slug === slug);
}

export const BADGES: BadgeDef[] = [
  { id: "first-run", name: "First Run", description: "Finish your first game.", tier: "bronze" },
  { id: "streak-7", name: "On Fire", description: "Log in 7 days in a row.", tier: "silver" },
  { id: "top-10", name: "Top Ten", description: "Place top 10 on any daily board.", tier: "gold" },
  { id: "all-rounder", name: "All-Rounder", description: "Legacy: scored in every launch game.", tier: "neon" },
];

/** Placeholder player shown until auth lands in Phase 2. */
export const MOCK_PLAYER: PlayerSummary = {
  username: "Guest",
  xp: 0,
  streakDays: 0,
  badges: [],
  gamesPlayed: 0,
  totalScore: 0,
};
