/** "What's new" on the home page: the latest updates, newest first. Add a line when something ships. */
export interface Update {
  tag: string;
  title: string;
  body: string;
  href: string;
}

export const UPDATES: Update[] = [
  { tag: "Graphics update · NextX · ZLink+", title: "WareForge looks the part: NextX Engine graphics", body: "A real sky with sun, clouds and stars that lights the whole yard; sharp, anti-aliased pictures with sun shadows on phones, and ambient occlusion, glowing lamps and the NextX colour grade on big screens. Polished concrete floors, metal-clad walls with a blue fascia, dock shelters round every door with red and green dock lights, wooden pallets under labelled cartons, curtain-sider trucks in their carrier's colours, proper forklifts with masts and chains, grass, asphalt, a chain-link fence and trees. Pick Auto, High, Medium or Low in the menu.", href: "/nextx/play/wareforge" },
  { tag: "Mega super update · NextX · ZLink+", title: "WareForge: your money on show, a bank, the cold chain and your own trucks", body: "Your cash is now always on the top bar, on every phone and screen, and it pops +$1,240 as money comes in. Tap it for the new bank: cash by the hour, today's profit, and loans to borrow and pay back. Carriers now take 6% of each shipment, so build a depot and run your own trucks. A cold chain: freezer racks, ice cream, seafood and vaccines that spoil if they warm up, and a new site, the Polar Cold Store in the snow. Three missions a day and an end-of-day report, customers who turn Bronze, Silver and Gold, VIP orders, Mk II machines, forklift drivers who level up, 8 upgrades and 8 goals. Plus storm rain and falling snow, a follow camera, photo mode, sounds and first-shift tips.", href: "/nextx/play/wareforge" },
  { tag: "Super mega update · NextX · ZLink+", title: "WareForge: the Mega hall, rail and day and night", body: "The map expands: open a Mega hall 78 bays long with up to eighteen doors, and lay a rail siding where freight trains bring sixteen pallets at a time for less. Two new sites, Harbor Gate by the container cranes and the Summit Mega DC. Forklifts now run on batteries and drive to charging bays. Copper and battery cells, motors and battery packs, a Motor Winder, a Cell Pack Line and a Robot Cell that builds e-bikes, camera drones and laptops. Contracts with bonuses, a market that moves every day, and events: storms, strikes, power cuts, heatwaves, shopping rushes and tech booms. 13 new upgrades (AGVs, solar, robotics, cross-docking, insurance and more) and 12 new goals. And a far better-looking yard: sunrise to night with floodlights and glowing lamps, roof trusses, shrink-wrapped goods, workers on the floor, an office, a gatehouse that lifts for trucks, a car park, and a river, a harbor or hills round every site.", href: "/nextx/play/wareforge" },
  { tag: "NextX · ZLink+", title: "NextX games now play in the NextX app", body: "WareForge, YourGov and Zero City are still part of ZLink+, and now they launch inside the NextX app: its own bar, the game on a big stage, its details and its members' leaderboard, all behind liquid glass.", href: "/nextx" },
  { tag: "New game · NextX · ZLink+", title: "WareForge: warehouse, production and manufacturing", body: "The third NextX title. Run a distribution centre or a factory in 3D: accept orders, and forklifts pick the pallets onto the lanes behind a dock door while a truck backs on to be loaded; follow every shipment from confirmed to delivered. Buy stock or raw materials, lay out racks and floor blocks, build presses, saws, SMT lines and assembly cells that turn steel, plastic, timber and parts into bicycles, chairs, helmets, smartphones and tool kits. Three sites, fourteen upgrades, twelve goals, a five-day season and a bright liquid-glass interface built for your phone.", href: "/nextx/play/wareforge" },
  { tag: "New app", title: "NextX: next generation game production", body: "Meet NextX, the label for Zero X's biggest games, with an app of its own. YourGov and Zero City are its first two titles: photoreal 3D worlds, deep simulations and interfaces built for your phone first. Open the app for the library, the NextX standard and every update to its games.", href: "/nextx" },
  { tag: "Two super mega updates · ZLink+", title: "YourGov: make it yours, and a whole society", body: "226 new features. Write and announce your own policies, then deliver them or face a U-turn; design your own executive orders, events and crises; rebrand your party; shape your leader; write speeches; rename the country, its offices, ministries and regions; declare national holidays; name and amend your bills. Plus a living society (crime, health, schools, housing, the environment, trust), industries and trade, protests, seasons and sport, summits and treaties, battlegrounds and candidates, a shadow cabinet, filibusters, the State of the Nation, 13 new laws, a command palette, an inbox, photo mode and save slots. And typing no longer pauses the game.", href: "/nextx/play/yourgov" },
  { tag: "Super mega update · ZLink+", title: "YourGov: markets, courts, whips and your legacy", body: "The biggest YourGov update yet. A real economy with inflation, interest rates, a stock market and a credit rating; whips and rebels in your own party; a top court that can strike down your laws, with judges you nominate; social media and rival leaders with personalities; an annual party conference; a weekly front page; a fast-forward button; difficulty levels and a sandbox; and at the end, your legacy and a hall of fame.", href: "/nextx/play/yourgov" },
  { tag: "Mega update · ZLink+", title: "YourGov: the campaign update", body: "A YouGov-style polling centre: voting intention by voter group and by region, leader ratings, the issues that matter and seat projections you commission. Hire a campaign team of six, publish a manifesto before each election and be held to it, write the budget area by area when you're in charge, face Question Time every few weeks, handle party scandals, move your party on the compass, give your election-night speech and chase 28 achievements.", href: "/nextx/play/yourgov" },
  { tag: "Mega update · ZLink+", title: "YourGov: the mega mega update", body: "Politics goes far beyond the ballot box. Win over eight voter groups and the interest groups behind them, court the press, keep your party's three factions happy or face a leadership challenge, and go head to head in TV debates before every election. In power, pick your cabinet, decide eighteen kinds of crisis, use executive actions, call referendums, keep your coalition partners' deals and manage relations abroad. Plus a diary to plan events weeks ahead, a region picker and week strip built for phones, fundraisers you can always hold, every event twice a week, scrolling fixed everywhere, a portrait layout and a fresh look.", href: "/nextx/play/yourgov" },
  { tag: "Mega update · ZLink+", title: "YourGov: twelve real countries and a scenario studio", body: "Govern the United States, the United Kingdom, Canada, Australia, Germany, France, Spain, Italy, Japan, India, Brazil or Mexico: real maps with real regions, cities and mountains, the real parties with their regional strongholds and today's seats, and each country's own system, from the Electoral College and the Senate's thirds to Westminster, coalition talks, the Bundesrat and two-round elections. Or make your own country in the new scenario studio: generate the land, found the parties, write the constitution and share it with a code.", href: "/nextx/play/yourgov" },
  { tag: "Mega update · ZLink+", title: "YourGov 2.0: a photoreal country and laws of your own", body: "YourGov is rebuilt. Avalon is now a photoreal 3D country you can fly over: mountains with snow, rivers, farmland, forests and cities, a real sky and a sea with surf, with the politics painted county by county onto the land. The chamber is 3D too, with every member at their desk and the votes lighting up as they come in. A new Liquid Glass interface, poll and economy charts, sound, and the law studio: write your own laws, set their options and what they do, and put them to the vote.", href: "/nextx/play/yourgov" },
  { tag: "New game · ZLink+", title: "YourGov: lead a party, win the country", body: "A new ZLink+ exclusive politics sim. Lead one of six parties across sixteen states and hundreds of counties: hold rallies and TV interviews, write bills on thirty laws and steer them through committee, the House, the Senate and the President, vote, pass the budget and keep your promises. Every two years the country votes, and you watch it come in county by county.", href: "/nextx/play/yourgov" },
  { tag: "Retiring", title: "Zenith retires on 30 November", body: "Zenith, our first city builder, is retiring. ZLink+ members can keep playing until 30 November 2026, when it closes for good. Its successor, Zero City, does everything Zenith did and much more, and ZLink+ now includes YourGov too.", href: "/games/zenith" },
  { tag: "Mega update", title: "Zero City 1.1: traffic, streets and spectacle", body: "Junctions take turns fairly, big crossings get demand-driven traffic lights, cars change lanes for their next turn, and a new Junctions tool sets lights, stops or give way. Roads join cleanly at proper angles. A new look with sky lighting and reflections, clouds, natural grass, swaying trees, glossy cars and depth of field. And politics in the streets: protests, strikes, floods, festivals, campaign billboards and election-night fireworks.", href: "/nextx/play/zero-city" },
  { tag: "Biggest update yet", title: "Zero City 1.0: Statecraft", body: "The politics app grows from 9 pages to 16: a department budget voted every two days, mayoral decrees, six lobbies, four newspapers and a TV channel with press conferences and an interactive debate, opposition leaders with their own bills and attack ads, party factions and leadership challenges, multi-stage crises, a legacy of achievements and titles, and district-by-district election nights.", href: "/nextx/play/zero-city" },
  { tag: "Mega update", title: "Zero City: Mandate, the politics app", body: "Mayor mode gets a full politics side app: electoral districts, a party with its own funds, headquarters and politicians, members who rebel unless whipped, votes of no confidence, daily party polls, a political compass and the city's own newspaper.", href: "/nextx/play/zero-city" },
  { tag: "DLC", title: "Zero City: the Riviera expansion", body: "Three coastal maps with a sunny new building style, plus a marina, a lighthouse, a casino and a beach resort. 50 ZX Cash, once.", href: "/nextx/play/zero-city" },
  { tag: "Mega update", title: "Zero City: Roadworks and Parliament", body: "Roads wear out under traffic until depot crews close a lane and resurface them. Mayor mode gets a 15-seat parliament with five parties, coalitions, political capital, 24 laws across six ministries, referendums, a cabinet with scandals and a campaign trail.", href: "/nextx/play/zero-city" },
  { tag: "Mega update", title: "Zero City: the Metropolis update", body: "Grow from a hamlet to a megalopolis through eight milestones, unlock five landmarks (a hospital, a museum, a university, a stadium and a landmark tower) that bring tourists, fight building fires with fire stations, and read your city with new info views. Empty zones no longer glare at night.", href: "/nextx/play/zero-city" },
  { tag: "Update", title: "Lifeline: Quick rooms and the emergency department", body: "24 ready-made rooms you place in one click, triage and ambulance bays, an incoming radio that shows every ambulance and helicopter before it arrives, and emergencies: Code Blues, major incidents and fires.", href: "/games/lifeline" },
  { tag: "Mega update", title: "Lifeline: the mega update", body: "Research, six new departments (ICU, maternity, psychiatry, MRI, a lab and a helipad), air ambulances, eight new conditions, machines that break down, staff who level up, a five-scenario campaign with medals and weekly awards.", href: "/games/lifeline" },
  { tag: "New game", title: "Lifeline", body: "Build a hospital in 3D: foundations, walls and rooms built by your workmen, doctors and nurses to hire, and patients with real conditions to diagnose, treat and send home. Lives saved is your score.", href: "/games/lifeline" },
  { tag: "ZLink+", title: "Zero City: Mayor mode", body: "Run Zero City as its mayor: a real budget and taxes, five groups of voters, a council that votes on your policies, dilemmas, promises and an election every term. Plus a new liquid-glass interface.", href: "/nextx/play/zero-city" },
  { tag: "ZLink+", title: "Zero City", body: "A new members-only city builder: ten maps, roads in eight draw modes with bridges and roundabouts, four kinds of zone, and a living low-poly city of cars, buses and people. Eight languages.", href: "/nextx/play/zero-city" },
  { tag: "New app", title: "Cash Cup", body: "Neon Siege tournaments for ZX Cash: 55 fighters on a map four times the size, 250 for the win and 3 per elimination. 10 to enter; the battle pass gives two free entries.", href: "/cash-cup" },
  { tag: "Mega update", title: "Coins are now ZX Cash", body: "A fresh start for everyone: balances, ZLink+, the battle pass, unlocks, XP and game saves are back to zero. Earn ZX Cash from daily rewards, the free lane and Cash Cups.", href: "/shop" },
  { tag: "ZLink+", title: "Zenith: build a city", body: "The ZLink+ flagship: a photoreal city builder. Roads, zones, power, water and services; a skyline that lights up at night, from Hamlet to Metropolis.", href: "/games/zenith" },
  { tag: "ZLink+", title: "Linkwave and more", body: "A members-only game, +25% XP, a weekly ZX Cash drop and link levels from Bronze to Neon. Neon Siege stays separate.", href: "/zlink" },
  { tag: "New", title: "ZLink+ is here", body: "One link, every plus: all of Sports+, UBusiness Ultimate and double daily ZX Cash for 40 ZX Cash a month. (Neon Siege stays separate.)", href: "/zlink" },
  { tag: "Site", title: "A whole new look", body: "Arcade noir: a drifting aurora, a synthwave hero, cards that tilt toward you, a game ticker and a glass navbar, in both themes.", href: "/" },
  { tag: "UBusiness", title: "Families, foodies and a food critic", body: "Six kinds of shopper, staff who get better (and training to five stars), a coffee bar, bulk deals, late-night opening, a price promise and the week in review.", href: "/games/ubusiness" },
  { tag: "UBusiness", title: "The big expansion + free Ultimate", body: "Bakery and frozen departments, specials, store upgrades, loans, trophies, reviews, shoplifters and a rival store. Ultimate is free to claim until 31 October.", href: "/games/ubusiness" },
  { tag: "Site", title: "A fresh new look", body: "A spotlight on the front page, Browse by vibe collections, and search everything with Ctrl+K.", href: "/" },
  { tag: "New game", title: "UBusiness", body: "Run your own store in photoreal 3D: stock the shelves, set the prices, work the till. Lite 5 ZX Cash, Ultimate 30, or free with the battle pass.", href: "/games/ubusiness" },
  { tag: "Hometown", title: "100 new things to build", body: "Furniture, Decor and Outdoor: king beds, arcade cabinets, pool tables, aquariums, fireplaces, gazebos, trampolines, fountains, trees and fences.", href: "/games/hometown" },
  { tag: "Hometown", title: "Townsfolk and servers", body: "Twelve townsfolk walk the streets, chat and keep the market trading while you're away. Pick your server from the menu: two more are on the way.", href: "/games/hometown" },
  { tag: "Mega update", title: "Daily rewards", body: "ZX Cash every day you come back, 50 on day 7.", href: "/" },
  { tag: "Hometown", title: "The Town Bank", body: "Save your cash for interest, claim the daily allowance, wave and cheer at your neighbours, find your way with the minimap.", href: "/games/hometown" },
  { tag: "Life", title: "Invest, adopt, go viral", body: "Shares and property that rise and fall, pets that love you back, fame on social media and holidays around the world.", href: "/games/life" },
  { tag: "Neon Siege", title: "New guns", body: "The Marksman Rifle and the Light Machine Gun now drop from floor loot and chests.", href: "/games/neon-siege" },
  { tag: "Trenches", title: "Belleau Wood", body: "A seventh front: summer wheat fields, a dense wood and a ruined lodge. Win there for the Belleau Oak Leaf.", href: "/games/trenches" },
  { tag: "Screamer", title: "Coach mode and Grand Final day", body: "Run a club from the box, roll premierships into a dynasty, and lift the cup to fireworks.", href: "/games/aussie-rules" },
];
