/**
 * The in-game update notes: every feature of the customisation update and the mega super
 * update, by section. Content lists (laws, events, crises, orders, achievements) come from the
 * game's own data so the notes can't drift from what's in the game.
 */
import { LAWS, EVENTS } from "../data";
import { ACHIEVEMENTS } from "../campaign";
import { CRISES, ORDERS } from "../politics";

export const NEW_LAWS = ["wealthTax", "rentControl", "retirementAge", "fourDayWeek", "nationalService", "publicBroadcaster", "dataPrivacy", "aiRules", "animalWelfare", "sugarTax", "prisonReform", "compulsoryVoting", "parliamentTerm"];
export const NEW_EVENTS = ["podcast", "phoneBank", "billboard", "localRadio", "matchDay", "hospital", "smallBiz", "festival", "feast", "marketDay", "commuters", "treePlant", "thinkTank", "volunteers"];
export const NEW_CRISES = ["heatwave", "quake", "dataLeak", "bridge", "detained", "skirmish", "foodPrices", "nurses", "spill", "crash"];
export const NEW_ORDERS = ["nurses", "rentFreeze", "schoolMeals", "redTape", "trees", "lobbyBan", "cyberShield", "seniorsCard"];
export const NEW_ACHIEVEMENTS = ["delivered", "delivery", "rebrand", "myOrder", "myEvent", "summit", "treaty", "peace", "defector", "oppDay", "filibuster", "gotv", "holiday", "safe", "longLives", "nation"];

export interface NoteSection {
  update: "custom" | "mega" | "app";
  title: string;
  icon: string;
  items: string[];
}

export function updateNotes(): NoteSection[] {
  const named = <T extends { id: string }>(list: T[], ids: string[], f: (x: T) => string) => ids.map((id) => list.find((x) => x.id === id)).filter((x): x is T => !!x).map(f);
  return [
    {
      update: "custom",
      title: "Your own policies",
      icon: "📣",
      items: [
        "Write your own policies: a name, an icon and a line on what they do",
        "Ten policy areas, from health to technology",
        "Set a policy's running cost",
        "Set what it does to happiness, growth and jobs",
        "Policies improve (or worsen) society's indices",
        "Pick the voter groups it's for, and against",
        "Choose your own deadline to deliver it",
        "The ambition meter: the more a policy does, the more it has to cost",
        "Eighteen policy templates to start from",
        "Announce a policy: a launch that lifts your campaign and the groups it's for",
        "Deliver it in government",
        "Junior partners need the senior party's say-so to deliver",
        "U-turns: drop a policy, at a price in trust and goodwill",
        "Broken promises when a deadline passes",
        "Delivered policies keep running, and costing, every year",
        "End a running programme to save the money",
        "Your policy book: announced, running, dropped and broken",
      ],
    },
    {
      update: "custom",
      title: "Executive orders, events and crises of your own",
      icon: "🖋️",
      items: [
        "Write your own executive orders",
        "Set an order's effect on approval, happiness, the budget, growth and jobs",
        "Pick the voter groups an order wins or loses",
        "Choose how long before an order can be used again",
        "Court risk grows with an order's power",
        "Four order templates",
        "Sign your orders from the studio or the government panel",
        "Edit and delete your orders",
        "Design your own campaign events",
        "Regional, national or party events of your own",
        "Your events can win support, money, members, unity and a voter group's goodwill",
        "Risky events cost less: prices are worked out for you",
        "A new Yours tab in the Events panel",
        "Plan your own events in the diary",
        "Write your own crises, with two or three choices",
        "{region} and {partner} fill themselves in",
        "The crisis checker: every choice must cost something",
        "Your crises strike at random: never, sometimes or often",
      ],
    },
    {
      update: "custom",
      title: "Your party and your leader",
      icon: "🎨",
      items: [
        "Rename your party",
        "A new short name",
        "A new colour (the map and the chamber repaint)",
        "A slogan",
        "An emoji logo",
        "Relabel your politics",
        "Rebrand rules: a cost, a cool-down, and rivals' colours protected",
        "A live preview of the new brand",
        "Rename your leader",
        "A nickname",
        "A catchphrase (say it in a speech for a little lift)",
        "Eleven backgrounds, each with a natural constituency",
        "Background perks: charisma, the press, unity, debates, Question Time, fundraising and crises",
        "A new look for your portrait",
      ],
    },
    {
      update: "custom",
      title: "Speeches, names and holidays",
      icon: "🎤",
      items: [
        "The speech writer: twelve themes",
        "Four tones: hopeful, fiery, sober, humble",
        "Three lengths (long speeches can ramble)",
        "Write the line the papers quote",
        "Address the nation in government, or give a major speech in opposition",
        "Rename the country",
        "Rename the head of government",
        "Rename the party leader's title",
        "Rename the President",
        "Rename both houses, and their short names",
        "Rename every ministry",
        "Rename every region (kept in your save)",
        "Create up to three national holidays",
        "Holidays lift the country every year",
      ],
    },
    {
      update: "custom",
      title: "Bills, laws and posts",
      icon: "📜",
      items: [
        "Name your bills (“The Clean Air Act”)",
        "Amend your own bill before it's voted on",
        "Law studio: say which voter groups care about your law",
        "Law studio: eight more templates",
        "Law studio: copy any built-in law as a starting point",
        "Up to twenty laws of your own (it was ten)",
        "Write your own social media posts",
      ],
    },
    {
      update: "custom",
      title: "Settings and saves",
      icon: "⚙️",
      items: [
        "Accent colour",
        "Text size",
        "Compact mode",
        "Calm mode (no animations)",
        "Hide the news ticker",
        "Hide the missions card",
        "Ask before ending a week with a vote waiting",
        "Choose how far skipping ahead goes",
        "A colour-blind friendly map",
        "Three save slots",
        "Export your game to a file",
        "Import a game from a file",
      ],
    },
    {
      update: "mega",
      title: "Society",
      icon: "🏙️",
      items: [
        "A society dashboard",
        "Crime",
        "Health",
        "Schools",
        "The environment",
        "Housing affordability",
        "Inequality",
        "Infrastructure",
        "Trust in politics",
        "Life expectancy",
        "Society follows the laws",
        "Society moves the economy and how happy people are",
        "Society shapes the issues voters care about",
        "A history chart for every index",
      ],
    },
    {
      update: "mega",
      title: "Industry and the world",
      icon: "🌐",
      items: [
        "Farming",
        "Manufacturing",
        "Services",
        "Technology",
        "Energy",
        "Laws move the industries",
        "Industries lift (or drag) growth",
        "The trade balance",
        "House prices",
        "A global economy that booms and busts",
        "Global recessions and booms in the news",
        "The world leaders' summit: lead, cooperate or walk out",
        "The climate summit: pledge, sign or walk out",
        "Six treaties to sign",
        "Pull out of a treaty",
        "Foreign aid levels",
        "Sanctions: impose and lift them",
        "State visits",
      ],
    },
    {
      update: "mega",
      title: "Protests, seasons and sport",
      icon: "✊",
      items: [
        "Ten kinds of protest movement",
        "Protests grow when they're ignored",
        "Meet the organisers",
        "Send in the police",
        "Give way (it becomes a promise)",
        "March with them in opposition",
        "The seasons (the southern hemisphere's run the other way)",
        "Seasonal crises: summer fires, winter strain",
        "The World Cup and the Olympic Games every two years",
        "Watch a match with the fans",
      ],
    },
    {
      update: "mega",
      title: "The campaign machine",
      icon: "🚌",
      items: [
        "Battleground regions",
        "Target up to five regions",
        "Candidate selection: local hero, star, loyalist or outsider",
        "Membership fees",
        "Campaign strategy: ground game, air war or digital first",
        "Get-out-the-vote drives",
        "Battle bus tours",
        "Your energy",
        "Take a holiday",
        "Health scares",
        "Newspaper endorsements",
        "Rival manifestos (and governments that follow them)",
      ],
    },
    {
      update: "mega",
      title: "Parliament and government",
      icon: "🏛️",
      items: [
        "A shadow cabinet",
        "Shadow readiness helps at Question Time and in debates",
        "Your shadow team takes office when you win",
        "Opposition days",
        "Win over members of other parties",
        "Your own members defect when the party is at war",
        "Filibusters",
        "Fast-track your bills",
        "Co-sponsor bills with another party",
        "The government's priority",
        "The State of the Nation address",
        "The honours list",
        "Public inquiries",
        "Emergency powers",
        "Civil service reform",
        "A one-tap reshuffle",
        "Call a confidence vote in yourself",
      ],
    },
    { update: "mega", title: "New laws", icon: "⚖️", items: named(LAWS, NEW_LAWS, (l) => `${l.name} (${l.options.map((o) => o.label).join(" · ")})`) },
    { update: "mega", title: "New events", icon: "🎪", items: named(EVENTS, NEW_EVENTS, (e) => `${e.icon} ${e.name}`) },
    { update: "mega", title: "New crises", icon: "🚨", items: named(CRISES, NEW_CRISES, (c) => `${c.icon} ${c.title.replace("{region}", "a region").replace("{partner}", "a neighbour")}`) },
    { update: "mega", title: "New executive orders", icon: "🖊️", items: named(ORDERS, NEW_ORDERS, (o) => `${o.icon} ${o.name}`) },
    { update: "mega", title: "New achievements", icon: "🏅", items: named(ACHIEVEMENTS, NEW_ACHIEVEMENTS, (a) => `${a.icon} ${a.name}: ${a.about.toLowerCase()}`) },
    {
      update: "app",
      title: "Getting around",
      icon: "🧭",
      items: [
        "The margin map: how close each county is",
        "The runner-up map: who's second everywhere",
        "The targets map: your battlegrounds and targets",
        "The command palette: search every panel and action",
        "The inbox: everything waiting on you",
        "Keyboard shortcuts",
        "Career stats",
        "Photo mode",
        "These update notes",
        "Help and a glossary",
        "The season in the date bar",
        "Fixed: typing in a text box no longer pauses the game",
      ],
    },
  ];
}

export const featureCount = () => updateNotes().reduce((a, x) => a + x.items.length, 0);

export const GLOSSARY: [string, string][] = [
  ["Approval", "How many people think the government is doing a good job. Governments rise and fall with it."],
  ["Happiness", "How content the country is. It follows the laws, the economy and society."],
  ["Unity", "How united your party is. Low unity brings rebels, defections and leadership challenges."],
  ["Goodwill", "How a voter group feels about you. Win it with events, laws and policies."],
  ["Battleground", "A region where you're within six points of the lead."],
  ["Policy", "A promise you write and announce. Deliver it in government before its deadline."],
  ["U-turn", "Dropping a policy you announced: it costs trust and goodwill."],
  ["Executive order", "An action the head of government takes without a vote. The courts may block strong ones."],
  ["Constitutional law", "A law that needs two thirds of each house to change."],
  ["Whip", "How hard your party pushes its members to vote the party line."],
  ["Filibuster", "Talking a bill out to delay its vote."],
  ["Opposition day", "A day the opposition picks the motion. Winning it embarrasses the government."],
  ["Shadow cabinet", "The opposition's team of would-be ministers."],
  ["Fast-track", "Rushing a government bill past its committee."],
  ["Co-sponsor", "Another party putting its name to your bill, and its votes behind it."],
  ["Get out the vote", "Knocking on doors on election day so your voters turn out."],
  ["Endorsement", "A newspaper or broadcaster backing a party before an election."],
  ["Energy", "How fresh you are. Events tire you; rest restores you."],
  ["Trust in politics", "Whether people believe politicians. Broken promises and scandals erode it."],
  ["Society indices", "Crime, health, schools, environment, housing, inequality, infrastructure and trust: 0 to 100."],
  ["Trade balance", "What the country sells abroad minus what it buys, as a share of the economy."],
  ["Inflation", "How fast prices are rising."],
  ["Credit rating", "What lenders think of the country's debts. A downgrade hurts."],
  ["Summit", "A meeting of world leaders, twice a year. The head of government decides how to play it."],
  ["Treaty", "A binding agreement with other countries."],
  ["Sanctions", "Penalties on another country: they cost a little growth while they last."],
  ["Protest", "A movement in the streets demanding a change to a law."],
  ["Emergency powers", "Eight weeks of extra power in a crisis, at a cost in trust."],
  ["State of the Nation", "The head of government's yearly speech to the country."],
  ["Referendum", "Putting a change to a law straight to the people."],
  ["Seat projection", "A poll that estimates every seat (an MRP)."],
];

export const SHORTCUTS: [string, string][] = [
  ["Enter or Space", "End the week"],
  ["1 – 9, 0", "Open the panels in the dock, in order"],
  ["/ or K", "The command palette"],
  ["I", "The inbox"],
  ["F", "Skip ahead"],
  ["H", "Photo mode (hide everything but the country)"],
  ["?", "Help"],
  ["P or Esc", "Pause"],
];
