/** Original question bank. Format: [prompt, correct answer, wrong, wrong, wrong]. */

export type TriviaCategory = "science" | "geography" | "space" | "nature" | "tech" | "math";

export const CATEGORY_LABELS: Record<TriviaCategory, string> = {
  science: "Science",
  geography: "Geography",
  space: "Space",
  nature: "Nature",
  tech: "Tech",
  math: "Math",
};

type Row = [string, string, string, string, string];

export const BANK: Record<TriviaCategory, Row[]> = {
  science: [
    ["Which gas do plants absorb from the air for photosynthesis?", "Carbon dioxide", "Oxygen", "Nitrogen", "Helium"],
    ["What is the chemical symbol for gold?", "Au", "Ag", "Go", "Gd"],
    ["How many bones are in the adult human body?", "206", "186", "226", "256"],
    ["Which part of a cell holds most of its genetic material?", "Nucleus", "Ribosome", "Membrane", "Cytoplasm"],
    [
      "Which force keeps the planets in orbit around the Sun?",
      "Gravity",
      "Magnetism",
      "Friction",
      "Static electricity",
    ],
    ["At sea level, water boils at what temperature?", "100 °C", "90 °C", "110 °C", "120 °C"],
    ["What is the hardest natural substance?", "Diamond", "Quartz", "Granite", "Topaz"],
    ["Which organ pumps blood around the body?", "Heart", "Liver", "Lungs", "Kidneys"],
    ["What is the most abundant gas in Earth's atmosphere?", "Nitrogen", "Oxygen", "Carbon dioxide", "Argon"],
    ["What is the chemical symbol for sodium?", "Na", "So", "Sd", "Sn"],
    ["Sound travels fastest through which of these?", "Steel", "Air", "Water", "A vacuum"],
    [
      "Which organelle is known as the powerhouse of the cell?",
      "Mitochondria",
      "Nucleus",
      "Golgi apparatus",
      "Vacuole",
    ],
    ["What pH value is neutral?", "7", "0", "5", "14"],
    ["What is H₂O more commonly called?", "Water", "Hydrogen peroxide", "Salt", "Ammonia"],
    [
      "What kind of energy does a moving object have?",
      "Kinetic energy",
      "Chemical energy",
      "Nuclear energy",
      "Elastic energy",
    ],
  ],
  geography: [
    ["What is the largest ocean on Earth?", "Pacific", "Atlantic", "Indian", "Arctic"],
    ["What is the capital of Japan?", "Tokyo", "Kyoto", "Osaka", "Sapporo"],
    ["What is the capital of Australia?", "Canberra", "Sydney", "Melbourne", "Perth"],
    ["Mount Everest sits on the border of Nepal and which country?", "China", "India", "Bhutan", "Pakistan"],
    ["On which continent is the Sahara Desert?", "Africa", "Asia", "Australia", "South America"],
    ["What is the capital of Canada?", "Ottawa", "Toronto", "Vancouver", "Montreal"],
    ["Which country has the largest land area?", "Russia", "Canada", "China", "United States"],
    ["What is the smallest continent by land area?", "Australia", "Europe", "Antarctica", "South America"],
    ["Which river flows through Cairo?", "Nile", "Congo", "Niger", "Tigris"],
    ["What is the capital of Brazil?", "Brasília", "Rio de Janeiro", "São Paulo", "Salvador"],
    ["In which country is the city of Marrakesh?", "Morocco", "Egypt", "Tunisia", "Algeria"],
    ["The Andes mountains run along which continent?", "South America", "Africa", "Asia", "Europe"],
    ["What is the capital of New Zealand?", "Wellington", "Auckland", "Christchurch", "Queenstown"],
    ["Which sea lies between Europe and Africa?", "Mediterranean Sea", "Red Sea", "Black Sea", "Caspian Sea"],
    ["Which is the longest river in South America?", "Amazon", "Paraná", "Orinoco", "Magdalena"],
  ],
  space: [
    ["Which planet is known as the Red Planet?", "Mars", "Venus", "Jupiter", "Mercury"],
    ["What is the largest planet in our solar system?", "Jupiter", "Saturn", "Neptune", "Earth"],
    ["Which planet is closest to the Sun?", "Mercury", "Venus", "Mars", "Earth"],
    ["What is the name of our galaxy?", "The Milky Way", "Andromeda", "Triangulum", "Sombrero"],
    [
      "Roughly how long does sunlight take to reach Earth?",
      "About 8 minutes",
      "About 8 seconds",
      "About 8 hours",
      "About 8 days",
    ],
    ["Which planet has the most prominent rings?", "Saturn", "Mars", "Mercury", "Venus"],
    ["Who was the first person to walk on the Moon?", "Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "John Glenn"],
    ["A space rock that burns up in the atmosphere as a streak of light is a…", "Meteor", "Comet", "Quasar", "Nebula"],
    ["Which is the hottest planet in our solar system?", "Venus", "Mercury", "Mars", "Jupiter"],
    ["How many planets are in our solar system?", "8", "7", "9", "10"],
    ["In which year did humans first land on the Moon?", "1969", "1965", "1972", "1959"],
    ["Which planet spins on its side, tilted about 98°?", "Uranus", "Neptune", "Saturn", "Mars"],
    ["What is the Sun mostly made of?", "Hydrogen", "Oxygen", "Iron", "Carbon"],
    ["Which planet is famous for its Great Red Spot storm?", "Jupiter", "Mars", "Saturn", "Neptune"],
    [
      "What is a group of stars forming a recognised pattern called?",
      "A constellation",
      "A galaxy",
      "A nebula",
      "An orbit",
    ],
  ],
  nature: [
    ["What is the largest mammal?", "Blue whale", "African elephant", "Whale shark", "Hippopotamus"],
    ["How many legs does a spider have?", "8", "6", "10", "12"],
    ["What do bees collect from flowers to make honey?", "Nectar", "Sap", "Dew", "Seeds"],
    ["What is a baby kangaroo called?", "Joey", "Kid", "Cub", "Pup"],
    ["What is the fastest land animal?", "Cheetah", "Lion", "Pronghorn", "Greyhound"],
    ["Animals that eat only plants are called…", "Herbivores", "Carnivores", "Omnivores", "Insectivores"],
    ["How many hearts does an octopus have?", "3", "1", "2", "4"],
    ["What is the largest species of big cat?", "Tiger", "Lion", "Jaguar", "Leopard"],
    ["Which tree produces acorns?", "Oak", "Maple", "Pine", "Birch"],
    [
      "What is the change from caterpillar to butterfly called?",
      "Metamorphosis",
      "Photosynthesis",
      "Migration",
      "Hibernation",
    ],
    ["Which animal is called the 'ship of the desert'?", "Camel", "Horse", "Elephant", "Donkey"],
    ["What is a group of wolves called?", "A pack", "A herd", "A flock", "A school"],
    ["What is the tallest animal?", "Giraffe", "Elephant", "Ostrich", "Moose"],
    ["In which hemisphere do almost all wild penguins live?", "Southern", "Northern", "Both equally", "Neither"],
    ["Which part of a plant absorbs water from the soil?", "Roots", "Leaves", "Petals", "Stem tips"],
  ],
  tech: [
    [
      "What does CPU stand for?",
      "Central Processing Unit",
      "Computer Power Unit",
      "Central Program Utility",
      "Core Processing Utility",
    ],
    [
      "What does HTML stand for?",
      "HyperText Markup Language",
      "High Transfer Machine Language",
      "Hyperlink Text Mode Language",
      "Home Tool Markup Language",
    ],
    ["How many bits are in a byte?", "8", "4", "16", "32"],
    [
      "What does URL stand for?",
      "Uniform Resource Locator",
      "Universal Routing Link",
      "Unified Remote Location",
      "User Resource Link",
    ],
    ["What is the binary number 101 in decimal?", "5", "3", "6", "101"],
    [
      "What does RAM stand for?",
      "Random Access Memory",
      "Read Access Memory",
      "Rapid Action Module",
      "Remote Array Memory",
    ],
    ["Which unit measures a screen's refresh rate?", "Hertz", "Watts", "Pixels", "Decibels"],
    [
      "What does GPU stand for?",
      "Graphics Processing Unit",
      "General Program Unit",
      "Graphical Power Utility",
      "Game Processing Unit",
    ],
    [
      "In programming, what is a 'bug'?",
      "An error in the code",
      "A type of cable",
      "A fast algorithm",
      "A cooling fan",
    ],
    [
      "What does AI stand for?",
      "Artificial Intelligence",
      "Automated Input",
      "Advanced Interface",
      "Analog Instruction",
    ],
    ["Which shortcut copies selected text on Windows?", "Ctrl + C", "Ctrl + V", "Ctrl + X", "Ctrl + Z"],
    [
      "What does USB stand for?",
      "Universal Serial Bus",
      "Unified System Board",
      "Universal Signal Bridge",
      "User Storage Bank",
    ],
    ["Software designed to harm a computer is called…", "Malware", "Firmware", "Freeware", "Middleware"],
    ["Pixels are the tiny dots that make up a…", "Digital image", "Sound file", "Network cable", "Battery cell"],
    ["Which number system uses only 0 and 1?", "Binary", "Decimal", "Hexadecimal", "Roman"],
  ],
  math: [
    ["What is 7 × 8?", "56", "54", "63", "48"],
    ["What is the square root of 81?", "9", "8", "7", "18"],
    ["How many sides does a hexagon have?", "6", "5", "7", "8"],
    ["What is 15% of 200?", "30", "15", "20", "45"],
    ["What is π rounded to two decimal places?", "3.14", "3.41", "3.12", "3.16"],
    ["How many degrees are in a right angle?", "90", "45", "180", "360"],
    ["What is 2 to the power of 10?", "1,024", "512", "2,048", "1,000"],
    ["What is the next prime number after 7?", "11", "9", "13", "10"],
    ["The angles of a triangle add up to how many degrees?", "180", "90", "270", "360"],
    ["What is 144 ÷ 12?", "12", "11", "14", "10"],
    ["What is the perimeter of a square with sides of 5?", "20", "25", "10", "15"],
    ["What is 0.5 as a fraction?", "1/2", "1/5", "5/1", "2/5"],
    ["Which number does the Roman numeral X represent?", "10", "5", "50", "100"],
    ["What is 9 × 9?", "81", "72", "99", "89"],
    ["How many minutes are in 2.5 hours?", "150", "125", "180", "90"],
  ],
};
